<?php
/**
 * Tawk.to
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to support@tawk.to so we can send you a copy immediately.
 *
 * @copyright   Copyright (c) 2016 Tawk.to
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$strToolTip = <<<EOT
catalog_category_view
catalog_product_view
cms_index_index
*
*/to/somewhere
/*/to/somewhere
/path/*/somewhere
/path/*/lead/*/somewhere
/path/*/*/somewhere
/path/to/*
/path/to/*/
/path/to/*/page
/*/to/*/page
/path/*/other/*
/path/*/other/*/
/http://www.example.com/
/http://www.example.com/*
/http://www.example.com/*/to/somewhere
/http://www.example.com/path/*/somewhere
/http://www.example.com/path/*/lead/*/somewhere
/http://www.example.com/path/*/*/somewhere
/http://www.example.com/path/to/*
/http://www.example.com/path/to/*/
/http://www.example.com/*/to/*/page
/http://www.example.com/path/*/other/*
/http://www.example.com/path/*/other/*/
EOT;
?>

<script type="text/x-magento-init">
    {
        "*": {
            "tawk-widget-select" : {
                "domain" : "<?= $block->escapeUrl($block->mainurl()) ?>",
                "baseUrl" : "<?= $block->escapeUrl($block->getBaseUrl()) ?>",
                "storedWidgetUrl" : "<?= $block->escapeUrl($block->getStoreWidget()) ?>",
                "removeWidgetUrl" : "<?= $block->escapeUrl($block->getRemoveUrl()) ?>",
                "form" : {
                    "key" : "<?= $block->escapeJs($block->getFormKey()) ?>",
                    "action" : "<?= $block->escapeUrl($block->getFormAction()) ?>"
                }
            }
        }
    }
</script>

<label for="websiteids" class="websiteids-label">Select Store</label>
<select name="websiteids" id="websiteids" class="websiteids">
<?= /* @noEscape */ $block->getWebSiteoptions(); ?>
</select>

<iframe
    id="tawk_widget_customization"
    style="border:none; width:100%; margin: 0; padding: 0; margin-top: 24px; min-height: 300px"
    src="<?= $block->escapeUrl($block->getIframeUrl()) ?>">
</iframe>

<div id="visibility_options">
    <div id="visibility" class="tawk-fields-group">
        <h3>Visibility Options</h3>
        <div class="tawk-fields tawk-fields-label">
            <label for="alwaysdisplay" class="websiteids-label">Always Display widget</label>
            <label class="switch">
                <input type="checkbox" id= "alwaysdisplay" name="alwaysdisplay"  class="tawk_check">
                <div class="slider round"></div>
            </label>
        </div>
        <div class="tawk-fields" id="exlucded_urls_container">
            <label for="excludeurl" class="tawk-ment">
                (Exception) hide tawk.to widget to the following URLs or paths.  List 1 item per line.<br>
                Layout handles (catalog_category_view, catalog_product_view, ...) are also supported. If a layout handle is present, others are ignored.<br>
            </label>
            <div class="tawk-tooltip">
                Examples of accepted patterns
                <ul class="tawk-tooltiptext">
                    <?php $lines = explode("\n", trim($strToolTip));?>
                    <?php foreach ($lines as $line):?>
                        <?php echo "<li>" . htmlspecialchars($line, ENT_QUOTES, 'UTF-8') . "</li>";?>
                    <?php endforeach;?>
                </ul>
            </div>
            <br />
            <textarea name="excludeurl" id="excludeurl" rows="10" class="tawk-urls"
                placeholder="<?php echo htmlspecialchars($strToolTip, ENT_QUOTES, 'UTF-8'); ?>"></textarea>
        </div>
        <div class="tawk-fields tawk-fields-label">
            <label for="donotdisplay" class="websiteids-label">Do not Display widget</label>
            <label class="switch">
            <input type="checkbox" value="0" id= "donotdisplay" name="donotdisplay"  class="tawk_check">
            <div class="slider round"></div>
            </label>
        </div>
        <div class="tawk-fields"  id="included_urls_container">
            <label for="includeurl" class="tawk-ment">
                (Exception) display tawk.to widget to the following URLs or paths. List 1 item per line.<br>
                Layout handles (catalog_category_view, catalog_product_view, ...) are also supported. If a layout handle is present, others are ignored.<br>
            </label>
            <div class="tawk-tooltip">
                Examples of accepted patterns
                <ul class="tawk-tooltiptext">
                    <?php $lines = explode("\n", trim($strToolTip));?>
                    <?php foreach ($lines as $line):?>
                        <?php echo "<li>" . htmlspecialchars($line, ENT_QUOTES, 'UTF-8') . "</li>";?>
                    <?php endforeach;?>
                </ul>
            </div>
            <br />
            <textarea name="includeurl" id="includeurl" rows="10" class="tawk-urls"
                placeholder="<?php echo htmlspecialchars($strToolTip, ENT_QUOTES, 'UTF-8'); ?>"></textarea>
        </div>
    </div>

    <BR />

    <div id="privacy" class="tawk-fields-group">
        <h3>Privacy Options</h3>
        <div class="tawk-fields tawk-fields-label">
            <label for="enable_visitor_recognition" class="websiteids-label">Enable Visitor Recognition</label>
            <label class="switch">
                <input type="checkbox" id="enable_visitor_recognition"
                    name="enable_visitor_recognition" class="tawk_check">
                <div class="slider round"></div>
            </label>
        </div>
    </div>

    <div class="tawk-fields">
        <a class="savesettingsbtn" href="#">Save Settings</a>
    </div>
</div>
